### ISSUE TITLE
[Request] Espanso

### ISSUE THREAD

**Issue by pointydev** [terrapkg/packages#1095]
**What software are you requesting to be packaged?**
Espanso - Cross-platform Text Expander written in Rust
https://github.com/espanso/espanso

**Describe the motivation**
The maintainers of the software have shown interest in RPM packaging (https://github.com/espanso/espanso/issues/1948), however are unfamiliar with best practices and distribution methods. Currently, the methods to update the application on RPM distros is by using the AppImage or by manually compiling, which require manually restarting the systemd service in order to update correctly. This could be streamlined by RPM packaging.

**Additional context**
Using Terra would skip the bureaucracy of the official repos, while also being easier than making a Copr. I also believe their maintainers would be able to learn a thing or two about properly creating RPMs themselves with Terra builds in place.

Thanks,
pointy

**Comment by AucaCoyan** [comment]
That would be awesome! I'm one of the maintainers of `espanso/espanso`, ask anything you need!
I currently don't know how to package RPM, as I don't use red hat yet 😢

**Comment by madonuko** [comment]
Thanks for the request; quick question, I've noticed there's [this AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=espanso-bin) that only depends on `xdotool` and `xclip` while [others depend on a lot more dependencies…](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=espanso): `bzip2`, `dbus`, `libgcc`, `openssl`, etc. So I'm not so sure which one is actually right.

**Comment by pointydev** [comment]
Compile dependencies are listed [in the documentation](https://espanso.org/docs/install/linux/#x11-compile), although Fedora specific ones are only [listed for Wayland](https://espanso.org/docs/install/linux/#wayland-compile), however I'm sure inferring this is easy enough.

**Comment by madonuko** [comment]
I did looked at that for the build dependencies, but I can't find any resources that talk about the install dependencies.
Anyway I'll just test it myself in the end.

**Comment by joh6nn** [comment]
In case it's helpful, this is the the dependency list from the .deb package:

 - libc6 (>= 2.27)
 - libdbus-1-3 (>= 1.9.14)
 - libx11-6
 - libxcb1
 - libxtst6
 - xclip
 - libnotify-bin
 - systemd
 - libxkbcommon0 (>= 0.5.0)
 - libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg) | libwxgtk3.2-1
 - libgcc1 (>= 1:4.2)
 - libstdc++6 (>=6)

**Comment by madonuko** [comment]
After digging into a bunch of references:

wayland: libxkbcommon dbus libnotify glibc wxGTK libgcc wl-clipboard
x11: libxkbcommon dbus libnotify glibc wxGTK libgcc xdotool xclip libX11 libXtst libxcb

Does this look good to you all?

**Comment by AucaCoyan** [comment]
Yup, sounds about right!

**Comment by xplosionmind** [comment]
Hi All!

I was looking at the [Terra repository for Fedora 41](https://repos.fyralabs.com/terra41-source/), and I do not see Espanso in it… Is there a way to make this package available for Fedora 41, too?

I have no packaging experience, but I would be very happy to help, at least with QA!
