### ISSUE TITLE
[BUG] Install guide on Website is different than here

### ISSUE THREAD

**Issue by boredsquirrel** [terrapkg/packages#1418]
**Describe the bug**
The install instructions on [the website](https://terra.fyralabs.com/) are different from the ones here, which is very confusing.

website:
```
sudo dnf install --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' --setopt='terra.gpgkey=https://repos.fyralabs.com/terra$releasever/key.asc' terra-release
```

here the install instructions are using a completely different method and path:

```
sudo dnf config-manager --add-repo https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
```

I suppose the website is outdated? Or where does this difference come from?

**Comment by korewaChino** [comment]
The one on the website downloads a release package which then provides the repo file. The other one uses `config-manager` to download the repo file into the configs.

It's recommended to download the repo release package so we can update the repo files when needed.
