### ISSUE TITLE
[BUG] Submarine images are corrupted

### ISSUE THREAD

**Issue by korewaChino** [terrapkg/packages#1427]
**Describe the bug**
The submarine kpart image is corrupt

**To Reproduce**
Flash image from `/usr/share/submarine` and attempt to boot it on a Depthcharge machine

**Affected (please complete the following information):**
`submarine`

**Comment by Owen-sz** [comment]
https://nightly.link/FyraLabs/submarine/workflows/build/main/submarine-x86_64.zip 
is a fixed build, RPM needs to be updated.

**Comment by korewaChino** [comment]
> https://nightly.link/FyraLabs/submarine/workflows/build/main/submarine-x86_64.zip is a fixed build, RPM needs to be updated.

We are not building from nightly CI, we're building from source.
