### ISSUE TITLE
[BUG] Stray package in terra 40

### ISSUE THREAD

**Issue by AMDmi3** [terrapkg/packages#1429]
**Describe the bug**
I've got a report of stray package `avs-tplg-conf` present in the package repository index but missing in the git repository:

```
% curl -s https://repos.fyralabs.com/terra40/repodata/9a514d4c8c37c51ef7ae0f39833ba6485e7bfc7f9434bfeee8daf6a7d6983cbb-primary.xml.gz | gunzip | grep -B1 -A26 '>avs-tplg-conf<'
<package type="rpm">
  <name>avs-tplg-conf</name>
  <arch>x86_64</arch>
  <version epoch="0" ver="2024.02" rel="1.fc40"/>
  <checksum type="sha256" pkgid="YES">20944fec0c889b69d896fc0b222338963c1a318a0276d63693f2f5be16f2068c</checksum>
  <summary>Configuration files for Intel AudioVoiceSpeech (AVS) driver</summary>
  <description>Configuration files for Intel AudioVoiceSpeech (AVS) driver. Each configuration file represents an audio stream topology i.e.: connections of AudioDSP pipelines and processing modules that provide rich user experience with the Intel AVS stack. The avs-driver is part of the Linux kernel sound subsystem, sound/soc/intel/avs.</description>
  <packager></packager>
  <url>https://github.com/thesofproject/avs-topology-xml</url>
  <time file="1716871349" build="1711599152"/>
  <size package="29191" installed="35710" archive="42020"/>
  <location href="avs-tplg-conf-0:2024.02-1.fc40.x86_64.rpm"/>
  <format>
    <rpm:license>Apache-2.0</rpm:license>
    <rpm:vendor></rpm:vendor>
    <rpm:group>Unspecified</rpm:group>
    <rpm:buildhost>8fc2d0f65aa9</rpm:buildhost>
    <rpm:sourcerpm>avs-tplg-conf-2024.02-1.fc40.src.rpm</rpm:sourcerpm>
    <rpm:header-range start="4504" end="12505"/>
    <rpm:provides>
      <rpm:entry name="avs-tplg-conf" flags="EQ" epoch="0" ver="2024.02" rel="1.fc40"/>
      <rpm:entry name="avs-tplg-conf(x86-64)" flags="EQ" epoch="0" ver="2024.02" rel="1.fc40"/>
    </rpm:provides>
    <rpm:conflicts>
      <rpm:entry name="alsa-sof-firmware"/>
    </rpm:conflicts>
  </format>
</package>
```

Package: https://repos.fyralabs.com/terra40/avs-tplg-conf-0:2024.02-1.fc40.x86_64.rpm

Yet there's no mention of avs-tplg-conf in the repository neither in `frawhide` nor in `f40` branch. Any idea what's going on?

**Comment by madonuko** [comment]
Sorry for the late respond, I saw you informed this in the [old repology request thread](https://github.com/repology/repology-updater/issues/1307) 2 days ago but I have been very sick recently and couldn't be bothered to formulate a proper response.

Anyway, the issue revolves around the fact that we have "removed" the package from Terra. Removing a package from Terra doesn't automatically mean the actual RPM is removed. Instead, only the sources are removed. This is why you can't find this in the repository. There are numerous reasons why we don't actually remove the RPM, but the main reason relates to backwards compatibility.

The actual "real" problem here I guess, is that the web server doesn't redirect users to the older commits that contain the sources. I'll push a fix probably next week.

**Comment by AMDmi3** [comment]
Got it, thank you!
