### ISSUE TITLE
[FYRA-397] policy: ban inline sources

### ISSUE THREAD

**Issue by lleyton** [terrapkg/packages#1450]
Example, look at terra-mock-configs, which currently have the actual mock configs in this repo alongside the spec file. This makes it hard for us to update them and keep them in sync with all branches. I'm proposing a policy addition to ban this, and move existing inline sources into their own versioned repo.

<sub>[FYRA-397](https://linear.app/fyra/issue/FYRA-397/policy-ban-inline-sources)</sub>

**Comment by madonuko** [comment]
What qualifies as inline sources?

[https://github.com/terrapkg/packages/blob/cc46576a58c55fa2b50be69d05216ca0281a0933/anda/games/opsu/opsu.spec#L28](https://github.com/terrapkg/packages/blob/cc46576a58c55fa2b50be69d05216ca0281a0933/anda/games/opsu/opsu.spec#L28)

This?
