### ISSUE TITLE
[Package Request] graalvm

### ISSUE THREAD

**Issue by lleyton** [terrapkg/packages#164]
**What software are you requesting to be packaged?**
https://www.graalvm.org/
https://github.com/graalvm

**Describe the motivation**
Graal is a performance focused implementation of the JVM (with many other neat features.) With it, I've gotten notable performance and memory improvements in Java applications, such as Minecraft. Besides being useful to have on its own, it might be a nice package to complement Prism Launcher, which requires a JVM. 

**Additional context**
There's also a [Graal updater tool](https://www.graalvm.org/22.1/reference-manual/graalvm-updater/) which seems to mange Graal versions and components. Maybe we could just package that?

Oracle also distributes an enterprise edition, although the licensing there would probably prevent us from distributing it directly.

**Comment by korewaChino** [comment]
I think we should just package GrallVM itself. Fedora packages individual versions of Rust and Node.js. They don't package rustup or nvm. Plus it might be kinda useful to just let users use GraalVM on runtime instead of having them manually install a version
