### ISSUE TITLE
[ULTIMATUM] komikku

### ISSUE THREAD

**Issue by korewaChino** [terrapkg/packages#1820]
Komikku already has a Flatpak on Flathub https://flathub.org/apps/info.febvre.Komikku, why do we have an RPM build available?

**Comment by korewaChino** [comment]
@runlevel5

**Comment by runlevel5** [comment]
@korewaChino each to their own. Flatpak is NOT available for all architectures (for example ppc64le). Additionally not all Fedora users prefer Flatpak to RPM.

**Comment by korewaChino** [comment]
We only build for aarch64 and x86_64, which the Flatpak build targets.

And there seems to be 0 advantage over running this app natively over running in Flatpak.

Our policy states that we only package desktop applications if it  provides an inherent advantage over running it inside a Flatpak (i.e system environment access in case of VSCodium or JRE access in the case of PrismLauncher). We refrain from packaging apps that already have Flatpak builds that provide no advantage running natively.

**Comment by nothingneko** [comment]
I also don't really see a scenario where someone would be running komikku on ppc64le. Are there even any consumer devices with it?

**Comment by korewaChino** [comment]
> I also don't really see a scenario where someone would be running komikku on ppc64le. Are there even any consumer devices with it?

Apart from old ppc macs and 6-7th gen console I see no other consumer POWER/PowerPC devices out there.

I mean there are POWER-based desktop workstations out there but most Linux distros don't even support them unless it's some big distro like Debian.

**Comment by nothingneko** [comment]
ppce64le and the PPC you're thinking of are different things. POWER is what we're talking about

**Comment by runlevel5** [comment]
> And there seems to be 0 advantage over running this app natively over running in Flatpak.

IMHO this is subjective and I do not want to bring up this debate. However I do believe we should offer users options

> I mean there are POWER-based desktop workstations out there but most Linux distros don't even support them unless it's some big distro like Debian.

Fedora has always been one of the best distro that support ppc64le

> We only build for aarch64 and x86_64, which the Flatpak build targets.

I am fully aware of that. However the SRPM could be fetched and built for platforms that Flatpak does not support.

> Our policy states that we only package desktop applications if it provides an inherent advantage over running it inside a Flatpak (i.e system environment access in case of VSCodium or JRE access in the case of PrismLauncher). We refrain from packaging apps that already have Flatpak builds that provide no advantage running natively.

In the end of the day, it is your project and you make the call and whatever the outcome it might be I will respect it.

**Comment by madonuko** [comment]
Personally we lose nothing from this at all; in fact we gain a new package maintainer / contributor. So I don't see why we need such an ultimatum.

If it was a package request, sure; but applying such a policy to a PR doesn't sound right to me.

**Comment by madonuko** [comment]
Since I don't acknowledge this ultimatum and there are no further replies/justification, I am marking this as invalid.
