### ISSUE TITLE
Terra 38 Failed Builds

### ISSUE THREAD

**Issue by windowsboy111** [terrapkg/packages#190]
# List of Failed Builds

- [x] #295
- [x] `libappimageupdate` (dep: `libappimage`)
- [x] `libappimagelauncher` (dep: `libappimage` `libappimageupdate`)
- [x] #290
- [x] #291
- [x] `libbismuth` ([gha](https://github.com/terrapkg/packages/actions/runs/4144588209/jobs/7167831816#step:5:6035))
- [x] `pop-launcher` (debugpkg)
- [x] `melody` (dep: `(python3dist(rich) < 13~~ with python3dist(rich) >= 12.5)`)
- [x] `gcm-core` (spec)
- [x] `rnote` ([gha](https://github.com/terrapkg/packages/actions/runs/4144588209/jobs/7167831163#step:5:6656))
- [x] `vala-panel-appmenu` (dep: `pkgconfig(vala-panel)`)
- [x] `elementary-greeter` (mutter)
- [x] `gala` (mutter)
- [x] `wingpanel` (mutter)
- [x] `unity-shell` (dep: `pkgconfig(libunity-settings-daemon)` `pkgconfig(nux-4.0)` `pkgconfig(unity-misc)`)
- [x] `unityx-shell` (dep: `pkgconfig(nux-4.0)` `pkgconfig(unity-settings-daemon)`)
- [x] `groovy` (dep: gendesk)
- [x] `gendesk` (dep: `xyproto-*`)

## Mutter
Missing: `pkgconfig(mutter-clutter-11)` `pkgconfig(mutter-cogl-11)` `pkgconfig(mutter-cogl-pango-11)`

**Comment by windowsboy111** [comment]
t38 will get a sync and full rebuild 6 h later, stay tuned (?)

**Comment by cat-master21** [comment]
It may be a good idea to have a test matrix for both Terra 37 and Terra 38/Rawhide so it is easier to see if the packages can be built ahead of time.

**Comment by windowsboy111** [comment]
> It may be a good idea to have a test matrix for both Terra 37 and Terra 38/Rawhide so it is easier to see if the packages can be built ahead of time.

see #228

**Comment by windowsboy111** [comment]
`melody`: deps are outdated; upstream issue.

**Comment by lleyton** [comment]
As discussed on the Discord, any new submissions besides critical fixes will be rejected from Terra 37. We'll be making 38 the default branch soon.

**Comment by madonuko** [comment]
Mass Rebuild is happening! See [Batch 1](https://github.com/terrapkg/packages/actions/runs/4713823697) and [Batch 2](https://github.com/terrapkg/packages/actions/runs/4713848484).

**Comment by madonuko** [comment]
[See here for all missing packages according to Repology](https://repology.org/projects/?search=&maintainer=&category=&inrepo=terra_37&notinrepo=terra_38&repos=&families=&repos_newest=&families_newest=).

- [x] appimagelauncher
- [x] libappimageupdate
- [x] libayatana-common
- [x] ayatana-indicator- : datetime, messages, notifications, sound
- [ ] #481 
- [x] #549 
- [x] gmenuharness
- [x] gsettings-qt
- [ ] libbismuth
- [x] libindicator
- [x] libusermetrics
- [x] lomiri
- [x] lomiri- : app-launch, download-manager, indicator-network, session, system-settings, url-dispatcher
- [x] qt5-qtdbustest
- [x] qtdbusmock
- [x] qtmir

**Comment by cat-master21** [comment]
These may not be in Terra, but are ones I at least have open PRs for.
* ~~qt5-qtdbustest~~
* ~~gsettings-qt~~
* ~~gmenuharness~~
* ~~libindicator~~ (replaced by terra-libindicator)
* ~~qtdbusmock~~
* ~~lomiri-app-launch~~
* ~~lomiri-url-dispatcher~~
* ~~lomiri-ui-toolkit~~
* ~~libusermetrics~~
* ~~lomiri-download-manager~~
* ~~lomiri-system-settings~~
ayatana-indicators will take some time until they should be rebuilt as they all depend on `libayatana-common` which needs lomiri-url-dispatcher which depends on a lot of other things.

**Comment by korewaChino** [comment]
What's the update on appimageupdate and appimagelauncher?

**Comment by korewaChino** [comment]
AppImage packages fixed by #643

**Comment by madonuko** [comment]
`blackbox-terminal` fails to build only because Fedora decided to include both gtk3 and gtk4 vapi files into `valac` which causes conflicts during compilaiton.

**Comment by madonuko** [comment]
libbismuth upstream issue.

Closing (blackboard tracking in pr)
