### ISSUE TITLE
[ULTIMATUM] anda/desktops/elementary/

### ISSUE THREAD

**Issue by madonuko** [terrapkg/packages#1954]
Deadline: **2024-09-01**

The specs, update scripts, and anything used to build this package **will be erased** from the repository.

The RPM package will be erased too if there are security concerns.

You may help stop this by solving the issue listed below.

## Issue
- Upstream Pantheon packages are unfortunately always not in sync with Fedora's packaging pace
  - e.g. mutter support is usually not up to date from Elementary
- Pantheon Desktop has been broken and deprecated since Ultramarine 40
- Internal Fyra discussions has deemed efforts to package Pantheon unviable due to its unpopularity not justifying the difficulty to maintain its stack

**Comment by lleyton** [comment]
If there's interest in someone picking up maintenance for this set of packages, let us know ASAP
