### ISSUE TITLE
[BUG] OpenTabletDriver needs .NET 6, spec requires .NET 8

### ISSUE THREAD

**Issue by Hexality** [terrapkg/packages#1957]
**Describe the bug**
OpenTabletDriver complains about not having .NET6.0 runtime installed when it was supposed to be upgraded to .NET8.0.

**To Reproduce**
1. Install '.NET 8.0 and OpenTabletDriver'
2. See error 'NETCore.App 6.0 not found'

**Expected behavior**
Run OTD with .NET 8.0 Runtime and/or SDK without having to rely on .NET 6.0 Runtimes and/or SDK.

**Affected (please complete the following information):**
 - Ultramarine 40
 - OpenTabletDriver v0.6.4.0+9f4e357910a5917ef86166c195c858c1c65b46d2

**Additional context**
.NET 6.0 has conflicting problems with .NET 8.0 (which I have talked about in #general chat of FyraLabs discord server), because of that migrating OTD to 8.0 was expected. However, today after I removed .NET 6 so I could update everything, OTD still complained about not having .NET 6.0 installed.

**Comment by madonuko** [comment]
Seems to be caused by the fact that it hasn't had a new release since Dec 2023. Should actually make this a nightly package.

**Comment by korewaChino** [comment]
Actually seems like .NET 8.0 can compile code for .NET 6.0 so maybe let's just add .NET 6.0 as a runtime dependency, this seems to be the case here since OTD is written with 6.0 in mind

**Comment by korewaChino** [comment]
Okay, update: Seems like upstream is only supporting .NET 6.0 for now, so our solution is to simply just change the dotnet runtime to 6.0
