### ISSUE TITLE
Pop launcher interfere with cosmic-desktop copr

### ISSUE THREAD

**Issue by wiiznokes** [terrapkg/packages#2111]
I use terra for the zed package, but i also have this [copr](https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/)  installed. I'm forced to pin pop-launcher to a specific version because the terra version seems to take the priority.

**Comment by wiiznokes** [comment]
Btw, it is likely than this copr will be available in Fedora packages sooner than latter. I would suggest to remove this package from your repo because the gnome version of cosmic is not maintained anymore

**Comment by madonuko** [comment]
The COPR uses the version format `0.1.0~^%{commitdate}git%{shortcommit}`, but the latest version on [`pop-launcher`](https://github.com/pop-os/launcher) is `1.2.1`.

Supposedly RPM will interpret `0.1.0~…` as something along the lines of "version smaller than 0.1.0 but larger than 0.0.1^…" (such as 0.1.0 alpha/beta/rc). The versioning is just weird or should I say incorrect.

**Comment by wiiznokes** [comment]
Yes, thanks for pointing this. I will just bump the version in the copr (i'm one of the maintainer)
