### ISSUE TITLE
[BUG] budgie-extras

### ISSUE THREAD

**Issue by sadlerm4** [terrapkg/packages#2246]
**Describe the bug**
Installing individual `budgie-applet*` packages may not install `budgie-extras-daemon` as dependency. It's not really a problem currently because both the `budgie-extras` metapackage and `budgie-extras-daemon` are dependencies of `ultramarine-flagship-filesystem`. However, this has the side effect of users of Flagship Edition not being able to remove any individual applets that they may not want. If you're going to the trouble of building separate packages for each applet, it makes sense to allow individual package removal.

**Suggested changes**
- `ultramarine-flagship-filesystem` - Change dependency on `budgie-extras` to recommends (won't change anything for builds because I believe `install_weak_deps=True` anyway)
- `ultramarine-flagship-filesystem` - Dependency on `budgie-applet-visualspace` (I think? this is actually the only truly essential package because it's used in UM Budgie default toolbar layout)
- `ultramarine-flagship-filesystem` - Remove dependency on `budgie-extras-daemon`
- `budgie-extras` - update specfile with which `budgie-applet*` packages depend on `budgie-extras-daemon`

**Affected (please complete the following information):**
 - UM Flagship Edition
 - `budgie-extras`, `ultramarine-flagship-filesystem`, `budgie-applet*`

-- 

If you're happy with these changes, I can open a PR on this repo for budgie-extras and a PR over on Ultramarine-Linux/packages for ultramarine-flagship-filesystem.

**Comment by madonuko** [comment]
Maybe we can test this out before UM41 release?

**Comment by sadlerm4** [comment]
Yeah I can do that:)
