### ISSUE TITLE
[BUG] obs-studio package on Terra is 31.0.0-beta1

### ISSUE THREAD

**Issue by craftnut** [terrapkg/packages#2494]
**Describe the bug**
Terra packages OBS Studio's beta releases

**Expected behavior**
OBS Studio package containing latest stable release

**Affected (please complete the following information):**
 - Ultramarine 41
 - obs-studio

**Comment by madonuko** [comment]
This package is from Fedora, not Terra.

**Comment by craftnut** [comment]
Ah my bad! Just switched over from years of Windows on desktop and mostly Arch and Ubuntu on laptop, still getting used to dnf package manager 😅
