### ISSUE TITLE
[Request] zsh-autocomplete

### ISSUE THREAD

**Issue by GildedRoach** [terrapkg/packages#2533]
**What software are you requesting to be packaged?**
https://github.com/marlonrichert/zsh-autocomplete

**Describe the motivation**
Ultramarine ships with Zsh pre-configured and syntax-highlighting/autosuggestions, this plugin adds additional useful behavior when paired with these. (Autosuggestions pulls suggestions from history, this pulls from the current directory and common commands.)

**Additional context**
Unsure if this is worth/desirable to be shipping by default in the case of Ultramarine, but I think having it available would be nice for Zsh users.

**Comment by madonuko** [comment]
is this different from `zsh-autosuggestions`?

**Comment by GildedRoach** [comment]
> is this different from `zsh-autosuggestions`?

Yes, it is. One of the features of this one is adding more control over the suggestions, so it works nicely together with it. If you access the history (with the up arrow key) you get a menu of recent history you can quickly chose to fill in and things like that. It's highly configurable so I haven't tested all of what it can do, but it is complementary rather than being a rehash of `autosuggestions`.
