### ISSUE TITLE
[BUG] Install script not working

### ISSUE THREAD

**Issue by HVinther** [terrapkg/packages#2716]
**Describe the bug**
On a fresh Fedora 41 I tried running the install script from the terra website
`sudo dnf install --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' --setopt='terra.gpgkey=https://repos.fyralabs.com/terra$releasever/key.asc' terra-release
`

This did not result in a valid url resulting in a 404 message. The "fancy install script" from https://developer.fyralabs.com/terra/installing yielded the same result.

Chaging $releasever to 41 resulted in a successful install process.

**To Reproduce**
1. Install Fedora 41
2. Open Terminal
3. `sudo dnf install --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' --setopt='terra.gpgkey=https://repos.fyralabs.com/terra$releasever/key.asc' terra-release
`

**Expected behavior**
Release version is auto selected and the "just paste and run"-command "just works".

**Screenshots**
![billede](https://github.com/user-attachments/assets/e62b50ff-d379-4f55-b5f3-4c6963a1d823)

**Affected (please complete the following information):**
 - Fedora 41

**Comment by madonuko** [comment]
This is a possible regression in dnf5 as noted in https://github.com/rpm-software-management/dnf5/issues/1941

The workaround for this is to replace `$releasever` with the system release version (e.g. 41) manually

**Comment by lleyton** [comment]
Thanks for the info! I'll update the website and docs such that releasever is templated outside of dnf, something like this?

```sh
sudo dnf install --repofrompath "terra,https://repos.fyralabs.com/terra$(rpm -E %fedora)" --setopt="terra.gpgkey=https://repos.fyralabs.com/terra$(rpm -E %fedora)/key.asc" terra-release
```

**Comment by madonuko** [comment]
I think it only happens with `--setopt`, not `--repofrompath`

**Comment by lleyton** [comment]
reopening, since the workaround we're using doesn't work on rawhide
