### ISSUE TITLE
Retrigger builds for f41 packages from Dec 14 to Dec 21

### ISSUE THREAD

**Issue by GarciaLnk** [terrapkg/packages#2728]
The builds triggered for f41 packages after https://github.com/terrapkg/packages/commit/3130ce49e6b3bd8ff0cefd27d8cb253e1ed64b62 up until https://github.com/terrapkg/packages/commit/de3fec95688c25b2260742c5c20d94f0586e5a87 were being targeted for rawhide instead of f41, this means that the packages added or updated during this time period haven't reached the f41 repo, and they never will until a rebuild is triggered (either automatically due to a new update or manually).

My suggestion is to manually trigger rebuilds for the affected packages to bring the f41 repo up to date.

**Comment by madonuko** [comment]
https://github.com/terrapkg/packages/actions/runs/12471765326
