### ISSUE TITLE
[BUG] Narrator & prismlauncher

### ISSUE THREAD

**Issue by lleyton** [terrapkg/packages#287]
**Describe the bug**
Versions of Minecraft that have a narrator (for accessibility) require libflite. Currently, this isn't specified as a dependency of prismlauncher.

**To Reproduce**
1. Install 'prismlauncher'
2. Try to use narrator

**Expected behavior**
Narrator to work.

**Affected (please complete the following information):**
 - Distro: Fedora/Ultramarine
 - Package: prismlauncher

**Comment by windowsboy111** [comment]
Make this recommended or… a dep?

**Comment by getchoo** [comment]
recommends probably since it isn't a hard requirement, but should still be a default. i'll add it now
