### ISSUE TITLE
Conflicting Packages

### ISSUE THREAD

**Issue by lleyton** [terrapkg/packages#37]
Some packages conflict with their Fedora counterparts. Unless there's a really good justification for this, they should be removed. See the following list:

- [x] dnf-plugins-core
- [x] #99
- [x] impallari-raleway-fonts
- [x] editorconfig
- [x] plank

**Comment by lleyton** [comment]
@korewaChino, since you added these packages, could you clarify why they're here?

**Comment by jn64** [comment]
This is a rough check for packages with conflicting names, between Fedora 37 release repo (`fedora`) and Terra (`terra`).

I have no opinion on what Terra should or should not do. This is only for information, as a Fedora user, to other users.

```
repoid  evr                                  name
fedora  0.3.5-4.fc37                         contractor
terra   0.3.5-1.fc37                         contractor
fedora  4.3.1-1.fc37                         dnf-plugins-core
terra   1:4.3.1-1.fc37                       dnf-plugins-core
fedora  4.3.1-1.fc37                         dnf-utils
terra   1:4.3.1-1.fc37                       dnf-utils
fedora  0.12.5-4.fc37                        editorconfig
terra   0.12.5-4.fc37                        editorconfig
fedora  0.12.5-4.fc37                        editorconfig-devel
terra   0.12.5-4.fc37                        editorconfig-devel
fedora  0.12.5-4.fc37                        editorconfig-libs
terra   0.12.5-4.fc37                        editorconfig-libs
fedora  6.1.0-3.fc37                         elementary-icon-theme
terra   7.1.0-1.fc37                         elementary-icon-theme
fedora  6.1.0-3.fc37                         elementary-icon-theme-gimp-palette
terra   7.1.0-1.fc37                         elementary-icon-theme-gimp-palette
fedora  6.1.0-3.fc37                         elementary-icon-theme-inkscape-palette
terra   7.1.0-1.fc37                         elementary-icon-theme-inkscape-palette
fedora  6.1.0-2.fc37                         elementary-onboarding
terra   7.0.1-1.fc37                         elementary-onboarding
fedora  4.025-10.20200310git98add57.fc37     impallari-raleway-fonts
terra   4.101-10.fc37                        impallari-raleway-fonts
fedora  4.025-10.20200310git98add57.fc37     impallari-raleway-fonts-doc
terra   4.101-10.fc37                        impallari-raleway-fonts-doc
fedora  37.8-1.fc37                          lorax
terra   38.3-1.fc37                          lorax
fedora  37.8-1.fc37                          lorax-docs
terra   38.3-1.fc37                          lorax-docs
fedora  37.8-1.fc37                          lorax-lmc-novirt
terra   38.3-1.fc37                          lorax-lmc-novirt
fedora  37.8-1.fc37                          lorax-lmc-virt
terra   38.3-1.fc37                          lorax-lmc-virt
fedora  37.8-1.fc37                          lorax-templates-generic
terra   38.3-1.fc37                          lorax-templates-generic
fedora  0.11.89-11.20210202.git013d051.fc37  plank
terra   0.11.89-11.20210202.git013d051.fc37  plank
fedora  0.11.89-11.20210202.git013d051.fc37  plank-devel
terra   0.11.89-11.20210202.git013d051.fc37  plank-devel
fedora  0.11.89-11.20210202.git013d051.fc37  plank-docklets
terra   0.11.89-11.20210202.git013d051.fc37  plank-docklets
fedora  0.11.89-11.20210202.git013d051.fc37  plank-libs
terra   0.11.89-11.20210202.git013d051.fc37  plank-libs
fedora  4.3.1-1.fc37                         python3-dnf-plugin-leaves
terra   1:4.3.1-1.fc37                       python3-dnf-plugin-leaves
fedora  4.3.1-1.fc37                         python3-dnf-plugin-local
terra   1:4.3.1-1.fc37                       python3-dnf-plugin-local
fedora  4.3.1-1.fc37                         python3-dnf-plugin-modulesync
terra   1:4.3.1-1.fc37                       python3-dnf-plugin-modulesync
fedora  4.3.1-1.fc37                         python3-dnf-plugin-post-transaction-actions
terra   1:4.3.1-1.fc37                       python3-dnf-plugin-post-transaction-actions
fedora  4.3.1-1.fc37                         python3-dnf-plugin-show-leaves
terra   1:4.3.1-1.fc37                       python3-dnf-plugin-show-leaves
fedora  4.3.1-1.fc37                         python3-dnf-plugin-versionlock
terra   1:4.3.1-1.fc37                       python3-dnf-plugin-versionlock
fedora  4.3.1-1.fc37                         python3-dnf-plugins-core
terra   1:4.3.1-1.fc37                       python3-dnf-plugins-core
fedora  1.0.4-2.fc37                         switchboard-plug-tweaks
terra   1.0.4-1.fc37                         switchboard-plug-tweaks
```
---

To produce this list, using a fresh F37 container:

```sh
$ toolbox create --distro fedora --release 37 f37-terra-test
$ toolbox run -c f37-terra-test sudo dnf -y upgrade
$ toolbox run -c f37-terra-test sudo dnf config-manager --add-repo https://terra.fyralabs.com/terra.repo
$ toolbox run -c f37-terra-test sh -c "export LC_ALL=C; sudo dnf -q --repo=fedora,terra repoquery --qf='%{repoid}\t%{evr}\t%{name}' | sort -k3,3 | uniq -f2 -D | column -t -N repoid,evr,name"
```

Notes/caveats:

- F37 updates repo (`updates`) was intentionally excluded to keep things simple.
- This doesn't account for package architecture. The query was done on an x86_64 system. The effect on results is unknown, since `terra` includes multiple arches and `fedora` does not (unless forced `dnf --forcearch=...`).
- These 6 lines were manually removed from the output (false positives, they're duplicates within `terra`, not conflicts with `fedora`):
  ```
  terra   2.2.0-1.fc37                         switchboard-plug-notifications
  terra   2.2.0-4.fc37                         switchboard-plug-notifications
  terra   2.2.0-1.fc37                         switchboard-plug-notifications-debuginfo
  terra   2.2.0-4.fc37                         switchboard-plug-notifications-debuginfo
  terra   2.2.0-1.fc37                         switchboard-plug-notifications-debugsource
  terra   2.2.0-4.fc37                         switchboard-plug-notifications-debugsource
  ```

**Comment by lleyton** [comment]
Thanks! Our [official policy](https://github.com/terrapkg/packages/wiki/Policy) is to avoid package conflicts with Fedora. I'll take a look at the list and figure out what we can do.

**Comment by korewaChino** [comment]
> @korewaChino, since you added these packages, could you clarify why they're here?

The lorax package is newer than any of the stable Fedora repos. It is from F38 and includes a patch where you could add `--isfinal` and `--bugurl` as arguments.


The DNF patch was for COPR, to add a patch in a PR I sent over that allows a config file to say what distro it actually is, fixing Ultramarine and tauOS when enabling COPR repos and resolving to EPEL instead.

**Comment by lleyton** [comment]
Maybe we could suffix those packages? Module stream?

As for the duplicates pointed out by @jn64, I updated the list accordingly. I do find it a bit strange how F37 still ships some elementary packages considering that they dropped support for pantheon/elementary in F37. As such, I didn't add those to the list, we probably want to talk to Pantheon SIG about that.

**Comment by korewaChino** [comment]
> Maybe we could suffix those packages? Module stream?
Probbaly, but *will*  you add modularity support for subatomic?

**Comment by lleyton** [comment]
*Depends if we want to do this with a module stream.*

**Comment by windowsboy111** [comment]
From internal discussions, we are considering the possibility of providing two different versions (or editions?) of Terra, in which the rawhide edition will ensure that there are no conflicts between any Fedora / Copr repositories.

**Comment by getchoo** [comment]
> the rawhide edition will ensure that there are no conflicts between any Fedora / Copr repositories

i hope this would end up in the F38 branch when that time comes as honestly, the patch made for `dnf-plugins-core` is not relevant to fedora to fedora itself. furthermore, with the use of epoch, it's not possible to use something like `dnf downgrade dnf-plugins-core` after removing the terra repo - this isn't a great experience for fedora users imo. something like `lorax` is more understandable since it would be easy to downgrade and will end up in F38 anyways, but i still think there could be an argument made here as i'm not sure having new arguments is worth replacing official fedora packages.

i think the best solution here would be to move the patched version of `dnf-plugins-core` to the ultramarine/tauOS repositories, as it is a fix for a distribution-specific issue - and from my point of view, this repository is meant to only extend official repositories, not replace - so that responsibility should fall on upstream

**Comment by korewaChino** [comment]
Not yet, `lorax` is required.

**Comment by lleyton** [comment]
I'd like to make this a focus again as we move into the F38 release cycle. I do get the need of having more up-to-date packages for certain things, but we should consider suffixing them or putting them into a seperate "overlay" repo.

**Comment by madonuko** [comment]
`lorax` has been removed from Terra 38.
