### ISSUE TITLE
[BUG] Plotinus should not depend on unityx-shell

### ISSUE THREAD

**Issue by hazel-bunny** [terrapkg/packages#395]
**Describe the bug**
Right now `dnf repoquery --depends plotinus` shows unityx-shell, but plotinus is merely a gtk3 module and shouldn't depend on it. If I use plotinus on KDE, I don't want unityx.

**To Reproduce**
1. `dnf repoquery --depends plotinus`

**Expected behavior**
unityx-shell shouldn't be there, like https://aur.archlinux.org/packages/plotinus

**Screenshots**

**Affected (please complete the following information):**
 - Fedora 38, probably also 37
 - plotinus

**Additional context**
Thank you for maintaining this repo

**Comment by cat-master21** [comment]
Sorry about that it I didn't know that Plotinus was taken by UnityX from https://github.com/p-e-w/plotinus (no indication at all!) previously Plotinus was dependant on UnityX. I will fix this later thank you for reporting.
