### ISSUE TITLE
[BUG] update-nightly workflow is broken

### ISSUE THREAD

**Issue by getchoo** [terrapkg/packages#416]
**Describe the bug**
title, seems to have been [failing](https://github.com/terrapkg/packages/actions/workflows/update-nightly.yml) for the past week

**To Reproduce**
n/a

**Expected behavior**
changes are saved and then committed to the repository

**Screenshots**
n/a

**Affected (please complete the following information):**
- all nightly packages

**Additional context**
seems this started appearing in b1bdcbaf0b387b94bce4420e20b6b5b12f9ca30d, which updated the docker image used to f38. i'm guessing this is what's at fault

**Comment by lleyton** [comment]
taking a look
