### ISSUE TITLE
Document our custom SRPM macros

### ISSUE THREAD

**Issue by lleyton** [terrapkg/packages#48]
See the [anda-srpm-macros package](https://github.com/terrapkg/packages/blob/main/anda/srpm-macros).

**Comment by getchoo** [comment]
not really sure where this would be placed, but i think under the "Automatic Updates" subsection of the wiki's "Contribute" page would be nice

or i could just make a PR and put it somewhere else 🥸

## Anda SRPM Macros
| Macro | Function |
| --- | --- |
| `%git_clone`  | Clones a git repository into a tarball given a URL and branch name <br><br> Example: `%git_clone https://github.com/<OWNER>/<REPO>.git main` |
| `%sccache_prep` | Enables `sccache` while building packages (should be placed in `%prep`) <br><br> Optional variables include: <ul> <li>`sccache_bucket`: name of an [S3 bucket](https://github.com/mozilla/sccache#s3) `sccache` will use for storage</li> <li>`sccache_endpoint`: Alternative to `sccache_bucket` that contains an endpoint URL</li> <li>`sccache_accesskey`: Access key ID for AWS (you can find it [here](https://docs.aws.amazon.com/sdk-for-rust/latest/dg/credentials.html)]. This value is exported to the build environment as `AWS_ACCESS_KEY_ID`</li> <li>`sccache_secret`: Secret access key for AWS, exported to the build enviornment as `AWS_SECRET_ACCESS_KEY`</li>  |
| `%cargo_prep_online` | Enables internet access for `cargo`. Replaces `%cargo_prep` and should be used in `%prep`
| `%cargo_prep_online_sccache` | Enables `sccache` and internet access for `cargo`. Replaces `%cargo_prep` and `%cargo_prep_online` - should be used in `%prep` |
