### ISSUE TITLE
[BUG] python-rich already packaged in official Fedora repo

### ISSUE THREAD

**Issue by mochaaP** [terrapkg/packages#492]
**Describe the bug**
<https://github.com/terrapkg/packages/blob/f38/anda/python/rich/python3-rich.spec> is automatically generated by pyp2rpm and not manually revised, regarding it was already packaged in official Fedora repo [here](https://src.fedoraproject.org/rpms/python-rich/blob/rawhide/f/python-rich.spec).

**To Reproduce**
1. Install a clean f38 chroot
2. `dnf install python3-rich`
3. Enable Terra repo
4. `dnf upgrade`

**Expected behavior**
`python3-rich` installed from `fedora`

**Affected (please complete the following information):**
 - Distro
   Fedora (validated on f38, rawhide)
 - Package
   `python-rich` (`python3-rich`)

**Comment by mochaaP** [comment]
cc @raboneko @windowsboy111

**Comment by madonuko** [comment]
Terra 38: `13.4.1-1`

Updates 38: `13.3.5-1`

Terra is far more up to date.

**Comment by lleyton** [comment]
Still doesn't change that the policy is to not conflict with Fedora. Is there anything in Terra that requires that version?

**Comment by lleyton** [comment]
Just checked with `sudo dnf repoquery --whatrequires python3-rich --repoid terra`, and the only package seems to be melody. That should work with the Fedora provided one, so there is no reason not to pull this.
