### ISSUE TITLE
dedicated workflow for nightly packages

### ISSUE THREAD

**Issue by getchoo** [terrapkg/packages#59]
with the website and wiki have been updated to advertise the nightly packages in this repo, i think it might be a good time to make a dedicated workflow for nightly packages. 

currently, nightly packages (namely `prismlauncher-nightly`, `prismlauncher-qt5-nightly`, and `openasar-canary`) check for a commit every 30 minutes like the regular packages. imo, this is a bad approach as it misses the point of the packages being considered "nightly," puts an unneeded load on gh actions, increases the likelihood of an unstable commit being pushed to users, and pushes more updates to them than they would probably ever use. a better solution here could be to use the current update.yml workflow but schedule it for every 12-24h for the nightly packages, as that would solve the aforementioned issues, as well as help users viewing the actions tab track nightly updates easier. it would also help mitigate a potential issue with `openasar-canary`'s chkupdate script (as the source we use isn't instantly updated when a new commit is pushed) and not bring up the previous issues found in the nightly prismlauncher packages' approach.

**Comment by windowsboy111** [comment]
I am a bit confused -- aren't nightly packages for obtaining the latest version so we should run it more often compared to normal ones?

**Comment by getchoo** [comment]
it is for getting newer versions, which would still be happening if this change was made as new commits - and thus updates - will pushed nearly every day, while releases are less common (and not as consistent, which justifies checking every 30 minutes). this change would bring the project more in line with the actual [definition](https://en.wikipedia.org/wiki/Daily_build) of nightly builds, and examples set by other projects (see: [firefox nightly](https://ftp.mozilla.org/pub/firefox/nightly/2022/12/) updating every 12 hours, [vlc nightly builds](https://nightlies.videolan.org/) updating daily, or [retroarch nightly builds](https://www.retroarch.com/?page=platforms) updating daily)

this is common for things referred to as "nightly," but currently the packages here are more similar to something like arch's `-git` packages, which isn't needed here imo due to my previous points

**Comment by lleyton** [comment]
Maybe we could have a separate nightly workflow, and filter packages ending in `-nightly` from the main one?

**Comment by windowsboy111** [comment]
not possible with current system. @lleyton can you transfer issue to anda repo?

**Comment by lleyton** [comment]
I can't transfer issues to other orgs :''(

**Comment by windowsboy111** [comment]
Latest anda now supports filters! (see FyraLabs/anda@2a5f8ece FyraLabs/anda@a0b63af FyraLabs/anda@fe4b5fe)

Also see [branch w/update](https://github.com/terrapkg/packages/tree/w/update).
