### ISSUE TITLE
[Request] Mattermost

### ISSUE THREAD

**Issue by dtrunk90** [terrapkg/packages#594]
**What software are you requesting to be packaged?**
https://mattermost.com
https://github.com/mattermost/desktop

**Describe the motivation**
It's not packaged for Fedora at all.

**Comment by nothingneko** [comment]
This is already available as a Flatpak. I can’t see a technical justification for packaging it as an RPM (per policy)

**Comment by korewaChino** [comment]
> I can’t see a technical justification for packaging it as an RPM (per policy)

I mean, we have Discord and Telegram packaged as RPMs

**Comment by dtrunk90** [comment]
Sandboxed apps always cause issues. I personally prefer non-sandboxed apps.

**Comment by nothingneko** [comment]
Personal preference is great, we’ll talk about how policy applies here internally

**Comment by madonuko** [comment]
Mattermost should work perfectly fine sandboxed. There are insufficient reasons to justify not using Mattermost under Flatpak, and thus the package will not be added to Terra.
