### ISSUE TITLE
[BUG] Unnecessary dependencies for pantheon dekstop

### ISSUE THREAD

**Issue by Drsheppard01** [terrapkg/packages#707]
Are `gnome-desktop3`, `gnome-shell`, `gnome-disk-utility` dependencies required for `elementary-greeter` and `pantheon-session-settings`?

**Comment by korewaChino** [comment]
they are

**Comment by madonuko** [comment]
CTX: the spec files for the Elementary / Pantheon packages haven't been modified much since they were ported from the official Fedora repositories (when Fedora removed Pantheon DE entirely)
