### ISSUE TITLE
[Request] Forge GNOME Shell Extension

### ISSUE THREAD

**Issue by nothingneko** [terrapkg/packages#789]
**What software are you requesting to be packaged?**
The name of the software and link to website (if it exists) and source code (if available).
https://github.com/forge-ext/forge

**Describe the motivation**
A clear and concise description of why you want this package. Would this provide value to other users?

Replace Pop!_Shell in UM39

**Additional context**
Add any other context about the package request here.

Pop!_Shell isn't out for GNOME 45 and may never come, this is to provide some sort of feature parity with UM38

**Comment by korewaChino** [comment]
references:
https://src.fedoraproject.org/rpms/gnome-shell-extensions/blob/rawhide/f/gnome-shell-extensions.spec
https://src.fedoraproject.org/rpms/gnome-shell-extension-bubblemail

**Comment by korewaChino** [comment]
oop, already packaged https://koji.fedoraproject.org/koji/packageinfo?packageID=38650
https://packages.fedoraproject.org/pkgs/gnome-shell-extension-forge/gnome-shell-extension-forge/
