### ISSUE TITLE
[Request] gh

### ISSUE THREAD

**Issue by korewaChino** [terrapkg/packages#793]
**What software are you requesting to be packaged?**
https://github.com/cli/cli

**Describe the motivation**
A clear and concise description of why you want this package. Would this provide value to other users?

**Additional context**
Add any other context about the package request here.

**Comment by madonuko** [comment]
Seems to be already in official Fedora repos?

**Comment by korewaChino** [comment]
no, github CLI is not in official repos?

**Comment by korewaChino** [comment]
nvm it is
