### ISSUE TITLE
[New] depthcharge-tools

### ISSUE THREAD

**Issue by nothingneko** [terrapkg/packages#810]
**What software are you requesting to be packaged?**
The name of the software and link to website (if it exists) and source code (if available).

https://github.com/alpernebbi/depthcharge-tools

**Describe the motivation**
A clear and concise description of why you want this package. Would this provide value to other users?

Required for Ultramarine Chromebook support

**Additional context**
Add any other context about the package request here.

May need a support package for Chrome hardware - We want to separate this so we can automate kernel building in Katsu

**Comment by ellyq** [comment]
BTW, you can build it as .noarch since there are no hard dependencies. That way it can be installed on both ARM64 and x86_64 :)
https://github.com/alpernebbi/depthcharge-tools/blob/95d17c444ae3a9dec1c51ead6301ed04777314b9/depthcharge_tools/mkdepthcharge.py#L335

**Comment by alpernebbi** [comment]
A few things are missing from @madonuko 's PR. Please:

- Install `systemd/90-depthcharge-tools.install` to `/usr/lib/kernel/install.d/`
- Install `systemd/depthchargectl-bless.service` to `/usr/lib/systemd/system/`
- Install `completions/_mkdepthcharge.bash` as `/usr/share/bash-completion/completions/mkdepthcharge`
- Install `completions/_depthchargectl.bash` as `/usr/share/bash-completion/completions/depthchargectl`
- Install `completions/_mkdepthcharge.zsh` to `/usr/share/zsh/vendor-completions/`
- Install `completions/_depthchargectl.zsh` to `/usr/share/zsh/vendor-completions/`
- Run `rst2man mkdepthcharge.rst | gzip >mkdepthcharge.1.gz` and install to `/usr/share/man/man1/`
- Run `rst2man depthchargectl.rst | gzip >depthchargectl.1.gz` and install to `/usr/share/man/man1/`

At least that's what I do for Debian, Fedora paths may be slightly different.

**Comment by ellyq** [comment]
Reporting on Fedora 39 (x86_64):

```
/usr/lib/kernel/install.d/
├── 10-devicetree.install
├── 20-grub.install
├── 50-depmod.install
├── 50-dracut.install
├── 51-dracut-rescue.install
├── 60-kdump.install
├── 90-loaderentry.install
├── 90-uki-copy.install
├── 92-crashkernel.install
├── 95-kernel-hooks.install
└── 99-grub-mkconfig.install
```
`/usr/lib/systemd/system/` seems to match Debian (well, it's systemd after all).

Same goes for:
`/usr/share/bash-completion/completions/*`

ZSH completion uses a different path on Fedora:
`/usr/share/zsh/$(version)/functions/` (in my case $(version) == 5.9

So correct path would be:
`completions/_mkdepthcharge.zsh` -> `/usr/share/zsh/5.9/functions/_mkdepthcharge`
`completions/_depthchargectl.zsh` -> `/usr/share/zsh/5.9/functions/_depthchargectl`

`/usr/share/man/man1/` matches Debian as well.

**Comment by nothingneko** [comment]
> A few things are missing from @madonuko 's PR. Please:
> 
> * Install `systemd/90-depthcharge-tools.install` to `/usr/lib/kernel/install.d/`
> * Install `systemd/depthchargectl-bless.service` to `/usr/lib/systemd/system/`
> * Install `completions/_mkdepthcharge.bash` as `/usr/share/bash-completion/completions/mkdepthcharge`
> * Install `completions/_depthchargectl.bash` as `/usr/share/bash-completion/completions/depthchargectl`
> * Install `completions/_mkdepthcharge.zsh` to `/usr/share/zsh/vendor-completions/`
> * Install `completions/_depthchargectl.zsh` to `/usr/share/zsh/vendor-completions/`
> * Run `rst2man mkdepthcharge.rst | gzip >mkdepthcharge.1.gz` and install to `/usr/share/man/man1/`
> * Run `rst2man depthchargectl.rst | gzip >depthchargectl.1.gz` and install to `/usr/share/man/man1/`
> 
> At least that's what I do for Debian, Fedora paths may be slightly different.

I think we should put these in a separate package, the intention was to use depthcharge-tools on the builders as well

**Comment by alpernebbi** [comment]
> /usr/share/zsh/$(version)/functions/ (in my case $(version) == 5.9)

Maybe `/usr/share/zsh/site-functions/` instead? `vendor-completions` seems to be a Debian thing...

> I think we should put these in a separate package, the intention was to use depthcharge-tools on the builders as well

They won't really do anything on non-Chromebook devices. The `.install` file only works if you set `layout=depthcharge-tools` in `/etc/kernel/install.conf`, the `.service` file only runs if you have `kern_guid=...` in kernel cmdline, and the rest are shell completions and manual pages useful for whoever has `depthchargectl`/`mkdepthcharge` installed.

**Comment by ellyq** [comment]
Traditionally if we want to follow Fedora's packaging scheme, we should package kernel hooks and systemd bless service with main package, then:

- `depthcharge-tools-bash-completion.noarch`
- `depthcharge-tools-zsh-completion.noarch`
- `depthcharge-tools-manpages.noarch`

I personally don't see much of a benefit in splitting those, but not sure if upstream would accept the package.



_On side note, I've joined Fedora project a few days back and are working on getting Chromebook-specific packages in upstream repositories (UCM configuration, ectool and so on). It takes a while to figure out what's what, but hopefully we can get this ball rolling. Folks seem excited to see someone working on ARM64 Chromebooks, and having support in upstream definitely will be better than what I was doing for the past 2 years (maintaining x86_64 downstream with postinstall configs and scripts)._

**Comment by madonuko** [comment]
I'll prefer putting everything into a single RPM file. At maximum we'll just make a new doc subpackage if necessary.

Man pages usually go with the binaries. (this is further shown by rpmlint)
